### ISSUE TITLE
Filename scheme does not save in subdirectories

### ISSUE THREAD

**Issue by Seaspider1** [groovesquid/groovesquid#31]
Mac OS X 10.10.1
Compared to the pre-update version,
<Artist?<Artist>/><Album?<Album>/><##?<##> - ><Title>.mp3
now causes the song to be saved in the download directory that is specified at the top of the preferences pane instead of in Artist/Album/Song directory format.  Instead of spaces, it uses underscores, too.
Ex:
Artist: Coldplay
Album: Parachutes
Song: Spies
Download Directory: Users/macowner/Downlaods/Groovesquid
Filename scheme: <Artist?<Artist>/><Album?<Album>/><##?<##> - ><Title>.mp3

Old Version before update:
Users/macowner/Downloads/Groovesquid/Coldplay/Parachutes/03 - Spies.mp3
New version:
Users/macowner/Downloads/Groovesquid/Coldplay_Parachutes_03_-_Spies.mp3

**Comment by gbhrdt** [comment]
Thanks for your bug report!
Fixed by #0d513a65924aa0209e6355615cb7545aa1a79165 and will be included in the next version.

**Comment by dgoldm** [comment]
The problem still exists in the new version (8.1).
(Windows XP)

**Comment by KaiQ** [comment]
also still exists on Linux (8.1)

**Comment by Seaspider1** [comment]
(8.1) still has it for Mac OS X 10.10.1, too.

**Comment by gbhrdt** [comment]
fix will be included in v0.8.2.. be prepared

**Comment by gbhrdt** [comment]
Just released v0.8.2, should be finally working now.

**Comment by Seaspider1** [comment]
Works perfectly.  Thank you!
